### ISSUE TITLE
Apps not displayed

### ISSUE THREAD

**Issue by ip512** [ivangabriele/vscode-heroku#28]
I'm trying to link workspace to heroku app, but list of apps is empty. I use heroku/7.19.4 linux-x64 node-v11.3.0   and vscode 1.30.1
When I run `heroku apps --all`, I can see my app correctly. 
Thank you for any help

**Comment by ivangabriele** [comment]
I will check that

**Comment by ivangabriele** [comment]
@ip512 Is it fixed on the last version ?

**Comment by ip512** [comment]
Hi, I can see one app now, which is a personal app, that I created after I open the issue, so I can't be sure the update fix the problem. I still can't see collaborated apps (apps I have access to but without being owner)

**Comment by ivangabriele** [comment]
@ip512 Indeed I didn't include the collaborative projects yet. It's in progress and I should publish that in a few days.

**Comment by ip512** [comment]
Thank you for the update :)

**Comment by ivangabriele** [comment]
Not yet @anthony0030 but thanks for the reminder, I'm in a bit of a rush at work these last weeks so I didn't work much on that.
